### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by renehsz** [renehsz/odin-sock#1]
Currently windows does not work. However Winsock is very much like Berkeley Sockets, there are just a few differences.

**Comment by bpunsky** [comment]
Currently making bindings for Winsock2, it's a lot more than the Berkeley sockets stuff

I'll PR the bindings to `core:win32` at some point

Then it would be easy to take these Berkeley sockets bindings, the Winsock stuff, and make some sort of `core:net/sockets`

**Comment by renehsz** [comment]
Sounds great.
I've updated this library to work with the newest released version of Odin.
By the way, I don't know if this library is even nearly complete (it might be, or it might not be, I don't have time to check).
